spring.application.name=Blacksmith Online Store API
#spring.jpa.open-in-view=false // Desabilita o Open Session in View para evitar problemas de Lazy Loading em producao

jwt.security.token.secret=${JWT_SECRET:senha-secreta}
jwt.security.token.expiration-time=${JWT_EXPIRATION_TIME:PT24H}
jwt.security.token.issuer=${JWT_ISSUER:orderManagement}

spring.datasource.url=jdbc:postgresql://localhost:5432/blacksmith_store
spring.datasource.username=postgres
spring.datasource.password=sua_senha

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data.sql

spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

# =========================== SWAGGER CONFIG ===========================
# Define o endpoint onde a documentacao OpenAPI (Swagger) estare disponivel
#springdoc.api-docs.path=/api-docs  
# Define a versao do OpenAPI usada na documentacao  
#springdoc.api-docs.version=openapi_3_1  
# Habilita a interface do Swagger UI  
springdoc.swagger-ui.enabled=true  
# Define o caminho da interface grefica do Swagger UI  
springdoc.swagger-ui.path=swagger-ui.html  
# Ordena as operacoes na interface do Swagger UI pelo metodo HTTP (GET, POST, etc.)  
#springdoc.swagger-ui.operationsSorter=method  
# Ordena as tags alfabeticamente na interface do Swagger UI  
#springdoc.swagger-ui.tagsSorter=alpha  
# Garante que os cabecalhos HTTP sejam corretamente repassados quando o app este atres de um proxy reverso (ex: Nginx, Kubernetes)  
server.forward-headers-strategy=framework

# =========================== SWAGGER CSS ===========================
spring.mvc.static-path-pattern=/static/**
spring.web.resources.static-locations=classpath:/static/
